#!/usr/bin/python3 -u

import socket
import argparse
import sys
import time

# @brief Function to send commands to enable a feature on a fob
# @param fob_bridge, bridged serial connection to fob
# @param package_name, name of the package file to read from
def enable(fob_bridge, package_name):

    # Connect fob socket to serial
    fob_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    fob_sock.connect(("ectf-net", int(fob_bridge)))

    # Open and read binary data from package file
    with open(f"/package_dir/{package_name}", "rb") as fhandle:
        message = fhandle.read()

    fob_sock.settimeout(1)
    # Send enable command to fob
    fob_sock.send(b"E")

    # Send package to fob
    fob_sock.send(message[0:8])
    time.sleep(0.01)
    fob_sock.send(message[8:16])
    time.sleep(0.01)
    fob_sock.send(message[16:24])
    time.sleep(0.01)
    fob_sock.send(message[24:32])
    time.sleep(0.01)
    fob_sock.send(message[32:])

    # Set timeout for if enable fails

    # Try to receive data - if failed, enabling failed
    enable_success = b""
    try:
        enable_success = fob_sock.recv(1)
        while True:
            enable_success += fob_sock.recv(1)
    except socket.timeout:
        print(enable_success)

    return 0


# @brief Main function
#
# Main function handles parsing arguments and passing them to program
# function.
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--fob-bridge", help="Bridge for the fob", type=int, required=True,
    )
    parser.add_argument(
        "--package-name", help="Name of the package file", type=str, required=True,
    )

    args = parser.parse_args()

    enable(args.fob_bridge, args.package_name)


if __name__ == "__main__":
    main()
