#!/usr/bin/python3 -u

import socket
import argparse
import sys
import time


# @brief Function to send commands to pair a new fob.
# @param unpairmed_fob_bridge, bridged serial connection to unpairmed fob
# @param pairmed_fob_bridge, bridged serial connection to pairmed fob
# @param pair_pin, pin used to pair a new fob
def pair(unpaired_fob_bridge, paired_fob_bridge, pair_pin):
    
    # Connect to both sockets for serial
    unpaired_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    unpaired_sock.connect(("ectf-net", int(unpaired_fob_bridge)))
    unpaired_sock.settimeout(1)

    paired_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    paired_sock.connect(("ectf-net", int(paired_fob_bridge)))
    paired_sock.settimeout(1)

    # Send pair commands to both fobs
    unpaired_sock.send(b"P")
    paired_sock.send(b"P")

    # Receive ack from the paired fob
    try:
        ack = paired_sock.recv(1)
        while ack != b"P":
            ack = paired_sock.recv(1)
        print("Paired fob started execution...")
    except socket.timeout:
        sys.exit("Failed to pair fob (1)")

    # Send pin to the paired fob
    time.sleep(0.002)
    pair_pin_bytes = str.encode(pair_pin)
    paired_sock.send(pair_pin_bytes)

    # Try to receive data - if failed, pairing failed
    pair_success = b""
    try:
        pair_success += unpaired_sock.recv(1)
        while True:
            pair_success += unpaired_sock.recv(1)
    except socket.timeout:
        print(pair_success)

    return 0


# @brief Main function
#
# Main function handles parsing arguments and passing them to pair
# function.
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--unpaired-fob-bridge",
        help="Bridge for the unpaired fob",
        type=int,
        required=True,
    )
    parser.add_argument(
        "--paired-fob-bridge",
        help="Bridge for the paired fob",
        type=int,
        required=True,
    )
    parser.add_argument(
        "--pair-pin", help="Program PIN", type=str, required=True,
    )

    args = parser.parse_args()

    pair(args.unpaired_fob_bridge, args.paired_fob_bridge, args.pair_pin)


if __name__ == "__main__":
    main()
